### ISSUE TITLE
Create pkg to simplify remote calls

### ISSUE THREAD

**Issue by aldeed** [ongoworks/launchdock#2]
Probably low priority, but eventually it would be nice to have a small pkg that encapsulates the `DDP.connect` and server-to-server RPCs. This would allow Meteor apps that communicate with the launcher to do so with normal function calls that wrap the remote method calls, maybe even in an object-oriented way.

**Comment by aaronjudd** [comment]
Closing.  `ongoworks/launchdock` is now deprecated and replaced by https://github.com/reactioncommerce/launchdock/
