### ISSUE TITLE
Change ENV variables easily

### ISSUE THREAD

**Issue by aldeed** [ongoworks/launchdock#24]
It should be simple to change ENV variables on the fly for an app instance.

I searched a bit and it seems that updating the environment variables in a running docker container isn't possible. This may be another good reason to have the containers run a custom script, which in turn runs the Meteor app. The script could support updating ENV and restarting the app without stopping the container.

**Comment by aaronjudd** [comment]
Closing.  `ongoworks/launchdock` is now deprecated and replaced by https://github.com/reactioncommerce/launchdock/
