### ISSUE TITLE
Verify presence of image on launch

### ISSUE THREAD

**Issue by aldeed** [ongoworks/launchdock#27]
In "ai/launch": when checking for best host, check whether the requested image is available (pulled or built) on each host. Prefer hosts that have the requested image. If none have the requested image, maybe either throw and error or pull the image on all hosts and put the launch request in a queue to happen after the image is pulled.

**Comment by aaronjudd** [comment]
Closing.  `ongoworks/launchdock` is now deprecated and replaced by https://github.com/reactioncommerce/launchdock/
