### ISSUE TITLE
Pull Image on this Host

### ISSUE THREAD

**Issue by aldeed** [ongoworks/launchdock#28]
On Hosts screen, for each host info panel, add a "Pull Image on this Host" button with a select list of all images. Point is to allow pulling a specific image on a specific host. (You can already pull a specific image on all hosts at once from the Images screen.)

**Comment by aaronjudd** [comment]
Closing.  `ongoworks/launchdock` is now deprecated and replaced by https://github.com/reactioncommerce/launchdock/
