### ISSUE TITLE
Check max for hosts

### ISSUE THREAD

**Issue by aldeed** [ongoworks/launchdock#31]
In `HostActions.getBest`, we should omit hosts with more containers than the defined `max`. If all hosts are maxed out, we probably should add some notice/error to the UI or send an e-mail or something? Maybe allow the user to configure what happens when the max is reached. Eventually the goal is to support dynamic scaling.

**Comment by aaronjudd** [comment]
Closing.  `ongoworks/launchdock` is now deprecated and replaced by https://github.com/reactioncommerce/launchdock/
