### ISSUE TITLE
App instance linking

### ISSUE THREAD

**Issue by aldeed** [ongoworks/launchdock#33]
Specify container linking (--link) at launch, which would allow, for example, launching a container from the `wordpress` image linked to a container from the `mysql` image, or Meteor container linked to mongodb container, etc.

The difficulty is that they'll always have to run on the same host server.

**Comment by aaronjudd** [comment]
Closing.  `ongoworks/launchdock` is now deprecated and replaced by https://github.com/reactioncommerce/launchdock/
