### ISSUE TITLE
Notification e-mails

### ISSUE THREAD

**Issue by aldeed** [ongoworks/launchdock#34]
Need to have a screen in the UI where you can select a notification type and enter e-mail addresses to be notified. Notifications should appear on the dashboard until dismissed, too.

Also need a form where they can enter the MAIL_URL to use for sending, which we can store in the DB.

**Comment by aaronjudd** [comment]
Closing.  `ongoworks/launchdock` is now deprecated and replaced by https://github.com/reactioncommerce/launchdock/
